FROM mariadb:lastest

COPY C:\Users\Roeland quentin\OneDrive - EPHEC asbl\deuxieme\admin système II\projet admin /docker-entrypoint-initdb.d/

ENV MYSQL_ROOT_PASSWORD admin
ENV MYSQL_DATABASE Woodytoys
ENV MYSQL_USER admin
ENV MYSQL_PASSWORD admin

EXPOSE 3306
