FROM ubuntu:latest

RUN apt-get update -y && apt-get upgrade -y
RUN apt-get install net-tools bind9 bind9-utils dnsutils nano -y

COPY named.conf /etc/bind/named.conf
COPY named.conf.options /etc/bind/named.conf.options
COPY named.conf.default-zones /etc/bind/named.conf.default-zones
COPY named.conf.local /etc/bind/named.conf.local
COPY db.internl2-7.ephec-ti.be /etc/bind/dbintern.l2-7.ephec-ti.be

EXPOSE 53/TCP
EXPOSE 53/UDP

CMD named -g

